name = "distracted-drivers-keras"
repo = "https://github.com/kimquy06/distracted-drivers-keras.git"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"kimquy06/distracted-drivers-keras" = "0.0.1"
